# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 清华大学 TUNA 镜像源
brand: TUNA mirrors
baseurl: "" # the subpath of your site, e.g. /blog
permalink: "/:categories/:title/"

# Build settings
highlighter: rouge
markdown: redcarpet

redcarpet:
    extensions: ["tables", "autolink", "strikethrough"]

sass:
    sass_dir: static/css

gems:
    - jekyll-babel

exclude: [Gemfile, Gemfile.lock, README.md]

# Content Related
new_mirrors: [cygwin, chakra, megia]
